services:
  backend-app:
    container_name: backend-app
    build: ./
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - db_api-network

volumes:
  postgres:

networks:
  db_api-network:
    external: true