services:
  delivery-DB:
    image: postgres:latest
    container_name: delivery-DB
    restart: always
    environment:
      POSTGRES_USER: DeliveryDB
      POSTGRES_PASSWORD: DeliveryDB@2024
      POSTGRES_DB: DeliveryDB
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"
    networks:
      - api-network

  api:
    container_name: backend-app
    build: ./ #build this directory where Dockerfile is
    restart: unless-stopped
    # environment:
    #   DATABASE_URL: "postgres://DeliveryDB:DeliveryDB@2024@localhost:5432/DeliveryDB"
    ports:
      - 8080:8080
    depends_on:
      - delivery-DB
    env_file:
      - ./.env
    networks:
      - api-network

volumes:
  postgres:

networks:
  api-network:
    driver: bridge