services:
  delivery-DB:
    image: postgres:latest
    container_name: delivery-DB
    restart: always
    environment:
      POSTGRES_USER: DeliveryDB
      POSTGRES_PASSWORD: DeliveryDB@2024
      POSTGRES_DB: DeliveryDB
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - api-network

volumes:
  postgres:

networks:
  api-network:
    driver: bridge