services:
  project-database:
    image: postgres:latest
    container_name: project-database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Pr0j3(t
      POSTGRES_DB: project
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - api-network

volumes:
  postgres:

networks:
  api-network:
    driver: bridge