on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: Install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        
    - name: connect, pull and deploy
      run: | 
      ssh admin@${{ secrets.SSH_HOST }}  << 'EOF'
      cd delivery-backend
      git checkout main
      git restore deploy.sh entrypoint.sh
      git pull
      chmod +x deploy.sh
      chmod +x entrypoint.sh
      ./deploy.sh
      EOF

    - name: cleanup
      run: rm -rf ~/.ssh
