on:
  push:
    branches:
      - main
    # tags:
    #   - '*'

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: Install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        
    - name: connect, pull and deploy
      run: | 
        ssh admin@${{ secrets.SSH_HOST }}  << 'EOF'
        cd delivery-backend
        git checkout main
        git restore deploy.sh entrypoint.sh
        git pull
        rm .env
        echo "*** Adding secrets ***"
        echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' >> .env
        echo 'JWT_SECRET=${{ secrets.JWT_SECRET }}' >> .env
        echo 'REFRESH_SECRET="${{ secrets.REFRESH_SECRET }}"' >> .env
        echo 'API_KEY="${{ secrets.API_KEY }}"' >> .env
        echo 'WEATHER_API_KEY="${{ secrets.WEATHER_API_KEY }}"' >> .env
        chmod +x deploy.sh
        chmod +x entrypoint.sh
        ./deploy.sh
        EOF

    - name: cleanup
      run: rm -rf ~/.ssh
